// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Solver = require("./Solver.bs.js");
var Vector2 = require("./Vector2.bs.js");
var NumericalSolution = require("./NumericalSolution.bs.js");

function farmerPosition(t) {
  return /* Vector2 */[
          1,
          t
        ];
}

function boarVelocity(boarSpeed, boarPosition, t) {
  return Vector2.$percent$star(boarSpeed / Vector2.norm(Vector2.$percent$neg(/* Vector2 */[
                      1,
                      t
                    ], boarPosition)), Vector2.$percent$neg(/* Vector2 */[
                  1,
                  t
                ], boarPosition));
}

function computeSolutionForBoarSpeed(boarSpeed, stepT) {
  return NumericalSolution.toFunction(Vector2.$percent$plus, Vector2.$percent$star, Solver.solve(/* tuple */[
                  0,
                  1
                ], /* Vector2 */[
                  0,
                  0
                ], stepT, (function (param, param$1) {
                    return boarVelocity(boarSpeed, param, param$1);
                  })));
}

function sameSpeedSolution(stepT) {
  return computeSolutionForBoarSpeed(1.0, stepT);
}

exports.farmerPosition = farmerPosition;
exports.boarVelocity = boarVelocity;
exports.computeSolutionForBoarSpeed = computeSolutionForBoarSpeed;
exports.sameSpeedSolution = sameSpeedSolution;
/* No side effect */
