// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

function getPoints(param) {
  var step = param[2];
  var min = param[0];
  var n = Math.floor((param[1] - min) / step) | 0;
  return $$Array.mapi((function (i, _) {
                return min + i * step;
              }), Caml_array.caml_make_vect(n, /* () */0));
}

function trace(param, f) {
  return $$Array.map(f, getPoints(/* tuple */[
                  param[0],
                  param[1],
                  0.01
                ]));
}

function roundFloat(f) {
  return Math.floor(f + 0.5);
}

function intAndDecimalPart(x) {
  var rounded = Math.floor(x + 0.5);
  var decimal = x - rounded;
  return /* tuple */[
          rounded | 0,
          decimal
        ];
}

exports.getPoints = getPoints;
exports.trace = trace;
exports.roundFloat = roundFloat;
exports.intAndDecimalPart = intAndDecimalPart;
/* No side effect */
