// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Block2$UiLibrary = require("ui-library/src/Block2.bs.js");
var Static$UiLibrary = require("ui-library/src/Static.bs.js");

function mkPath(color, path) {
  return /* record */[
          /* color */color,
          /* path */path
        ];
}

function mkBlock(configs) {
  var configs$1 = $$Array.of_list(configs);
  return Block2$UiLibrary.mapModel((function (arr) {
                return /* record */[/* paths */$$Array.mapi((function (i, x) {
                                return /* tuple */[
                                        Caml_array.caml_array_get(configs$1, i)[/* color */0],
                                        /* Path */[x]
                                      ];
                              }), arr)];
              }), Block2$UiLibrary.mapInit((function (init) {
                    return $$Array.map((function (c) {
                                  return Curry._1(c[/* path */1], init);
                                }), configs$1);
                  }), Static$UiLibrary.block));
}

exports.mkPath = mkPath;
exports.mkBlock = mkBlock;
/* No side effect */
